### PR TITLE
Support Static Site Generation

### PR DESCRIPTION
**Pull request by buttercat1791**
[ALEX-122](https://shadowysupercoding.atlassian.net/browse/ALEX-122?atlOrigin=eyJpIjoiNDI2M2YyZWViNTRkNDIzYmIwOGNjZWM3ZDdhYjRjZTIiLCJwIjoiaiJ9)

We want to be able to build the Svelte project as a static site so that it can be easily hosted on any server.

## Changes

- Use Svelte's [static adapter](https://github.com/sveltejs/kit/tree/main/packages/adapter-static) to build the project as a fully static set of web pages.
- Replace dynamic routes in which publications are identified by path parameters with static routes in which publications are identified by query parameters.
- Update links in the `ArticleHeader` component to use the query parameter pattern.

## Testing

Test this locally by running `npm run build` to build the static site, then `npm run preview` to view it.

We should also test hosting this on our server.

[ALEX-122]: https://shadowysupercoding.atlassian.net/browse/ALEX-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by SilberWitch** [comment]
All of the ToCs are upside-down, now.

**Review by Silberengel — CHANGES_REQUESTED** [review]
Pulled the PR. Works on my machine. :smile: 

But all of the ToCs are upside-down, now.

**Comment by buttercat1791** [comment]
Tables of Contents have their own story: [ALEX-50](https://shadowysupercoding.atlassian.net/browse/ALEX-50?atlOrigin=eyJpIjoiMDI3MmRmMTcyZDMyNGYyMjhiMzVjNWQ5OTMwZWU0YjkiLCJwIjoiaiJ9).  I'm okay with leaving them in a broken state for a time until we can definitively sort them out with that story.

[ALEX-50]: https://shadowysupercoding.atlassian.net/browse/ALEX-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Review by Silberengel — APPROVED** [review]

**Comment by limina1** [comment]
This also works for me :+1:

**Comment by Silberengel** [comment]
@limina1 don't forget to approve the changes here:

https://github.com/ShadowySupercode/gc-alexandria/pull/2/files

**Review by limina1 — APPROVED** [review]

**Comment by Silberengel** [comment]
@buttercat1791 We can go ahead and merge this.

**Comment by buttercat1791** [comment]
I'll merge it then!

As discussed in Slack, we'll want to investigate reducing the number of static pages in the final build and making the app more SPA-like for dynamic content.  But that can be a future PR.

**Pull request merged**
